from pathlib import Path

# ABOUT
about = Path(r'C:/Users/Administrator/travel-website/my-travel-site/app/about/page.tsx')
text = about.read_text(encoding='utf-8')
text = text.replace("const siteTitle = pickLocalized(settings?.siteTitle, lang) || 'Infinite Journeys';", "const siteTitle = 'ZSY Travel';")
text = text.replace("const siteDescription = pickLocalized(settings?.siteDescription, lang) || 'Tailor-made luxury travel experiences across China.';", "const siteDescription = lang === 'zh' ? 'ZSY Travel 是面向全球旅客的中国高端定制旅行品牌。' : 'ZSY Travel is a premium China travel brand for tailor-made journeys.';")
text = text.replace("const footerIntro = pickLocalized(settings?.footerIntro, lang) || siteDescription;", "const footerIntro = lang === 'zh' ? 'ZSY Travel 专注中国高端定制旅行；后台未填的部分会以测试标记显示。' : 'ZSY Travel focuses on premium tailor-made journeys across China; unfilled CMS content is marked as test content.';")
text = text.replace("const aboutPositioningItems = settings?.aboutPositioningItems?.length ? settings.aboutPositioningItems.map((item: string) => pickLocalized(item, lang)) : [];", "const aboutPositioningItems = settings?.aboutPositioningItems?.length ? settings.aboutPositioningItems.map((item: string) => markPlaceholder(pickLocalized(item, lang) || '待填写')) : [markPlaceholder('待填写：品牌定位 1'), markPlaceholder('待填写：品牌定位 2'), markPlaceholder('待填写：品牌定位 3')];")
text = text.replace("const aboutWhyItems = settings?.aboutWhyItems?.length ? settings.aboutWhyItems.map((item: any) => ({ title: pickLocalized(item?.title, lang), desc: pickLocalized(item?.desc, lang) })) : [];", "const aboutWhyItems = settings?.aboutWhyItems?.length ? settings.aboutWhyItems.map((item: any) => ({ title: markPlaceholder(pickLocalized(item?.title, lang) || '待填写'), desc: markPlaceholder(pickLocalized(item?.desc, lang) || '待填写') })) : [{ title: markPlaceholder('待填写：优势标题 1'), desc: markPlaceholder('待填写：优势说明 1') }, { title: markPlaceholder('待填写：优势标题 2'), desc: markPlaceholder('待填写：优势说明 2') }, { title: markPlaceholder('待填写：优势标题 3'), desc: markPlaceholder('待填写：优势说明 3') }, { title: markPlaceholder('待填写：优势标题 4'), desc: markPlaceholder('待填写：优势说明 4') }];")
about.write_text(text, encoding='utf-8')

# CONTACT
contact = Path(r'C:/Users/Administrator/travel-website/my-travel-site/app/contact/page.tsx')
text = contact.read_text(encoding='utf-8')
text = text.replace("const siteTitle = pickLocalized(settings?.siteTitle, lang) || 'Infinite Journeys';", "const siteTitle = 'ZSY Travel';")
text = text.replace("const footerIntro = pickLocalized(settings?.footerIntro, lang) || 'Tailor-made luxury travel experiences across China.';", "const footerIntro = lang === 'zh' ? 'ZSY Travel 专注中国高端定制旅行；空缺字段已加测试标记，方便继续填充。' : 'ZSY Travel focuses on premium tailor-made China journeys; empty areas are marked as test content for easy completion.';")
text = text.replace("const contactAddress = pickLocalized(settings?.address, lang) || 'China';", "const contactAddress = markPlaceholder(pickLocalized(settings?.address, lang) || (lang === 'zh' ? '待填写：办公地点 / 服务基地' : 'Location / service base to be filled'));" )
text = text.replace("const contactGuideItems = settings?.contactGuideItems?.length ? settings.contactGuideItems.map((item: string) => pickLocalized(item, lang)) : [];", "const contactGuideItems = settings?.contactGuideItems?.length ? settings.contactGuideItems.map((item: string) => markPlaceholder(pickLocalized(item, lang) || '待填写')) : [markPlaceholder(lang === 'zh' ? '待填写：出行月份 / 天数' : 'Travel month / length to be filled'), markPlaceholder(lang === 'zh' ? '待填写：人数与客群类型' : 'Traveler count / profile to be filled'), markPlaceholder(lang === 'zh' ? '待填写：目的地偏好与预算范围' : 'Destination preference / budget range to be filled')];")
text = text.replace("<InfoCard title=\"Email\" value={settings?.contactEmail || 'info@example.com'}", "<InfoCard title=\"Email\" value={markPlaceholder(settings?.contactEmail || '待填写：联系邮箱')}")
text = text.replace("<InfoCard title=\"Phone / WhatsApp\" value={settings?.contactPhone || settings?.whatsappNumber || '+86 123 4567 8900'}", "<InfoCard title=\"Phone / WhatsApp\" value={markPlaceholder(settings?.contactPhone || settings?.whatsappNumber || '待填写：电话 / WhatsApp')}")
text = text.replace("<InfoCard title=\"WeChat\" value={settings?.wechat || 'Please add in CMS'}", "<InfoCard title=\"WeChat\" value={markPlaceholder(settings?.wechat || '待填写：微信号')}")
contact.write_text(text, encoding='utf-8')

# FAQ
faq = Path(r'C:/Users/Administrator/travel-website/my-travel-site/app/faq/page.tsx')
text = faq.read_text(encoding='utf-8')
text = text.replace("const siteTitle = pickLocalized(settings?.siteTitle, lang) || 'Infinite Journeys';", "const siteTitle = 'ZSY Travel';")
text = text.replace("const footerIntro = pickLocalized(settings?.footerIntro, lang) || 'Tailor-made luxury travel experiences across China.';", "const footerIntro = lang === 'zh' ? 'ZSY Travel 专注中国高端定制旅行；FAQ 未填字段会显示测试标记。' : 'ZSY Travel focuses on premium tailor-made China journeys; unfinished FAQ content is marked as test content.';")
text = text.replace("        { question: 'Can you customize a private itinerary across multiple cities in China?', answer: 'Yes. We specialize in tailor-made journeys across China based on your travel goals and schedule.' },", "        { question: markPlaceholder(lang === 'zh' ? '待填写：FAQ 问题 1' : 'FAQ question 1 to be filled'), answer: markPlaceholder(lang === 'zh' ? '待填写：FAQ 回答 1' : 'FAQ answer 1 to be filled') },\n        { question: markPlaceholder(lang === 'zh' ? '待填写：FAQ 问题 2' : 'FAQ question 2 to be filled'), answer: markPlaceholder(lang === 'zh' ? '待填写：FAQ 回答 2' : 'FAQ answer 2 to be filled') },")
text = text.replace("{pickLocalized(settings?.faqTitle, lang) || 'Frequently Asked Questions'}", "{markPlaceholder(pickLocalized(settings?.faqTitle, lang) || (lang === 'zh' ? '待填写：FAQ 标题' : 'FAQ title to be filled'))}")
text = text.replace("{pickLocalized(settings?.faqSubtitle, lang) || 'Find answers to common questions about our tailor-made China journeys, booking process, and travel planning support.'}", "{markPlaceholder(pickLocalized(settings?.faqSubtitle, lang) || (lang === 'zh' ? '待填写：FAQ 副标题' : 'FAQ subtitle to be filled'))}")
text = text.replace("{pickLocalized(faq.question, lang)}", "{markPlaceholder(pickLocalized(faq.question, lang) || (lang === 'zh' ? '待填写：FAQ 问题' : 'FAQ question to be filled'))}")
text = text.replace("{pickLocalized(faq.answer, lang)}", "{markPlaceholder(pickLocalized(faq.answer, lang) || (lang === 'zh' ? '待填写：FAQ 回答' : 'FAQ answer to be filled'))}")
text = text.replace("{pickLocalized(settings?.faqCtaTitle, lang) || 'Still deciding what kind of trip fits you best?'}", "{markPlaceholder(pickLocalized(settings?.faqCtaTitle, lang) || (lang === 'zh' ? '待填写：FAQ CTA 标题' : 'FAQ CTA title to be filled'))}")
text = text.replace("{pickLocalized(settings?.faqCtaSubtitle, lang) || 'Whether you are planning for family travel, executive travel, private journeys or a culture-focused route, we can help translate your ideas into a clearer tailor-made China plan.'}", "{markPlaceholder(pickLocalized(settings?.faqCtaSubtitle, lang) || (lang === 'zh' ? '待填写：FAQ CTA 副标题' : 'FAQ CTA subtitle to be filled'))}")
faq.write_text(text, encoding='utf-8')

# ARTICLE
article = Path(r'C:/Users/Administrator/travel-website/my-travel-site/app/articles/[slug]/page.tsx')
text = article.read_text(encoding='utf-8')
text = text.replace("const siteTitle = pickLocalized(settings?.siteTitle, lang) || 'Infinite Journeys';", "const siteTitle = 'ZSY Travel';")
text = text.replace("const footerIntro = pickLocalized(settings?.footerIntro, lang) || 'Tailor-made luxury travel experiences across China.';", "const footerIntro = lang === 'zh' ? 'ZSY Travel 灵感内容页；缺少正文或字段时会显示测试标记。' : 'ZSY Travel insights page; missing fields are intentionally shown with test markers.';")
text = text.replace("const articleTitle = pickLocalized(article.title, lang) || 'Article';", "const articleTitle = markPlaceholder(pickLocalized(article.title, lang) || (lang === 'zh' ? '待填写：文章标题' : 'Article title to be filled'));" )
text = text.replace("{article.author && <span>{t.by} {article.author}</span>}", "<span>{t.by} {markPlaceholder(article.author || (lang === 'zh' ? '待填写：作者' : 'Author to be filled'))}</span>")
text = text.replace("{lang === 'zh' ? '内容暂未补充。' : 'No content available yet.'}", "{markPlaceholder(lang === 'zh' ? '待填写：文章正文' : 'Article body to be filled')}")
article.write_text(text, encoding='utf-8')

# TOUR
tour = Path(r'C:/Users/Administrator/travel-website/my-travel-site/app/tours/[slug]/page.tsx')
text = tour.read_text(encoding='utf-8')
text = text.replace("const siteTitle = pickLocalized(settings?.siteTitle, lang) || 'Infinite Journeys';", "const siteTitle = 'ZSY Travel';")
text = text.replace("const footerIntro = pickLocalized(settings?.footerIntro, lang) || 'Tailor-made luxury travel experiences across China.';", "const footerIntro = lang === 'zh' ? 'ZSY Travel 案例详情页；未填好的字段会显示测试标记。' : 'ZSY Travel case detail page; unfinished fields are displayed with test markers.';")
text = text.replace("const tourTitle = pickLocalized(tour.title, lang) || 'Tour';", "const tourTitle = markPlaceholder(pickLocalized(tour.title, lang) || (lang === 'zh' ? '待填写：案例标题' : 'Case title to be filled'));" )
text = text.replace("const tourDescription = pickLocalized(tour.description, lang) || (lang === 'zh' ? '定制路线简介待补充。' : 'Tour overview coming soon.');", "const tourDescription = markPlaceholder(pickLocalized(tour.description, lang) || (lang === 'zh' ? '待填写：路线概览' : 'Overview to be filled'));" )
text = text.replace("const tourHighlights = Array.isArray(tour.highlights) ? tour.highlights.map((item: any) => pickLocalized(item, lang)).filter(Boolean) : [];", "const tourHighlights = Array.isArray(tour.highlights) && tour.highlights.length ? tour.highlights.map((item: any) => markPlaceholder(pickLocalized(item, lang) || '待填写')).filter(Boolean) : [markPlaceholder(lang === 'zh' ? '待填写：亮点 1' : 'Highlight 1 to be filled'), markPlaceholder(lang === 'zh' ? '待填写：亮点 2' : 'Highlight 2 to be filled')];")
text = text.replace("const itinerary = Array.isArray(tour.itinerary)\n    ? tour.itinerary.map((day: any) => ({\n        day: day?.day,\n        title: pickLocalized(day?.title, lang),\n        description: pickLocalized(day?.description, lang),\n      }))\n    : [];", "const itinerary = Array.isArray(tour.itinerary) && tour.itinerary.length\n    ? tour.itinerary.map((day: any) => ({\n        day: day?.day,\n        title: markPlaceholder(pickLocalized(day?.title, lang) || (lang === 'zh' ? '待填写：行程标题' : 'Itinerary title to be filled')),\n        description: markPlaceholder(pickLocalized(day?.description, lang) || (lang === 'zh' ? '待填写：行程描述' : 'Itinerary description to be filled')),\n      }))\n    : [{ day: 1, title: markPlaceholder(lang === 'zh' ? '待填写：第 1 天行程' : 'Day 1 itinerary to be filled'), description: markPlaceholder(lang === 'zh' ? '待填写：第 1 天说明' : 'Day 1 description to be filled') }];")
text = text.replace("{tour.duration ? `${tour.duration} ${lang === 'zh' ? '天' : 'Days'}` : (lang === 'zh' ? '待定' : 'TBD')}", "{tour.duration ? `${tour.duration} ${lang === 'zh' ? '天' : 'Days'}` : markPlaceholder(lang === 'zh' ? '待填写：时长' : 'Duration to be filled')}")
text = text.replace("{tour.price ? `$${tour.price}` : (lang === 'zh' ? '沟通后确认' : 'On request')}", "{tour.price ? `$${tour.price}` : markPlaceholder(lang === 'zh' ? '待填写：预算' : 'Budget to be filled')}")
tour.write_text(text, encoding='utf-8')
