const linkTargetField = {
  name: 'linkTarget',
  title: '跳转到哪里 / Link target',
  type: 'string',
  options: {
    list: [
      { title: '不跳转 / No link', value: 'none' },
      { title: '联系页 / Contact', value: '/contact' },
      { title: '关于我们 / About', value: '/about' },
      { title: '常见问题 FAQ / FAQ', value: '/faq' },
      { title: '首页案例区 / Home cases', value: '#cases' },
      { title: '首页文章区 / Home articles', value: '#articles' },
      { title: '首页目的地区 / Home destinations', value: '#destinations' },
      { title: '首页服务区 / Home services', value: '#travel-styles' },
      { title: '首页人群方案区 / Audience solutions', value: '#audiences' },
      { title: '自定义链接 / Custom link', value: 'custom' },
    ],
    layout: 'dropdown',
  },
  initialValue: 'none',
}

const iconFields = [
  {
    name: 'iconType',
    title: '图标怎么来 / Icon source',
    type: 'string',
    description: '推荐优先用预设图标；如果想更个性，可以改成 Emoji 或上传图片/SVG。',
    options: {
      list: [
        { title: '选系统预设图标 / Preset icon', value: 'preset' },
        { title: '用 Emoji / Emoji', value: 'emoji' },
        { title: '上传图片 / SVG / Upload image or SVG', value: 'upload' },
      ],
      layout: 'radio',
    },
    initialValue: 'preset',
  },
  {
    name: 'presetIcon',
    title: '预设图标 / Preset icon',
    type: 'string',
    hidden: ({ parent }: any) => parent?.iconType !== 'preset',
    options: {
      list: [
        { title: '🧭 指南针 / Compass', value: 'compass' },
        { title: '🗺️ 地图 / Map', value: 'map' },
        { title: '📷 相机 / Camera', value: 'camera' },
        { title: '⭐ 星星 / Star', value: 'star' },
        { title: '🛡️ 保障 / Shield', value: 'shield' },
        { title: '💬 对话 / Chat', value: 'chat' },
        { title: '✈️ 飞机 / Plane', value: 'plane' },
        { title: '🏔️ 雪山 / Mountain', value: 'mountain' },
        { title: '❤️ 爱心 / Heart', value: 'heart' },
        { title: '⏰ 时间 / Clock', value: 'clock' },
      ],
      layout: 'dropdown',
    },
  },
  {
    name: 'emoji',
    title: 'Emoji 图标 / Emoji',
    type: 'string',
    hidden: ({ parent }: any) => parent?.iconType !== 'emoji',
  },
  {
    name: 'uploadedIcon',
    title: '上传图标图片 / SVG / Upload icon',
    type: 'image',
    hidden: ({ parent }: any) => parent?.iconType !== 'upload',
    options: { hotspot: true },
  },
]

const ctaFields = [
  { name: 'primaryButtonText', title: '主按钮文字（双语） / Primary button text', type: 'localizedString' },
  { ...linkTargetField, name: 'primaryButtonTarget', title: '主按钮跳转 / Primary button target' },
  { name: 'primaryButtonLink', title: '主按钮自定义链接 / Primary custom link', type: 'string', hidden: ({ parent }: any) => parent?.primaryButtonTarget !== 'custom' },
  { name: 'primaryButtonNewTab', title: '主按钮新窗口打开 / Open primary in new tab', type: 'boolean', initialValue: false },
  { name: 'secondaryButtonText', title: '次按钮文字（双语） / Secondary button text', type: 'localizedString' },
  { ...linkTargetField, name: 'secondaryButtonTarget', title: '次按钮跳转 / Secondary button target', initialValue: 'none' },
  { name: 'secondaryButtonLink', title: '次按钮自定义链接 / Secondary custom link', type: 'string', hidden: ({ parent }: any) => parent?.secondaryButtonTarget !== 'custom' },
  { name: 'secondaryButtonNewTab', title: '次按钮新窗口打开 / Open secondary in new tab', type: 'boolean', initialValue: false },
]

const enabledField = { name: 'enabled', title: '显示这个模块 / Show this section', type: 'boolean', initialValue: true }

export const sectionObjects = [
  {
    name: 'linkItem',
    title: '链接项 / Link item',
    type: 'object',
    fields: [
      { name: 'text', title: '文字（双语） / Text', type: 'localizedString' },
      { ...linkTargetField, name: 'target', title: '跳转到哪里 / Link target' },
      { name: 'href', title: '自定义链接 / Custom link', type: 'string', hidden: ({ parent }: any) => parent?.target !== 'custom' },
      { name: 'newTab', title: '新窗口打开 / Open in new tab', type: 'boolean', initialValue: false },
    ],
  },
  {
    name: 'iconLinkCard',
    title: '图标卡片 / Icon card',
    type: 'object',
    fieldsets: [
      { name: 'content', title: '1. 内容 / Content' },
      { name: 'icon', title: '2. 图标 / 图片 / Icon / Image' },
      { name: 'action', title: '3. 跳转 / Link' },
    ],
    fields: [
      { name: 'title', title: '标题（双语） / Title', type: 'localizedString', fieldset: 'content' },
      { name: 'description', title: '描述（双语） / Description', type: 'localizedText', rows: 3, fieldset: 'content' },
      ...iconFields.map((field) => ({ ...field, fieldset: 'icon' })),
      { name: 'backgroundImage', title: '背景图（可选） / Background image', type: 'image', options: { hotspot: true }, fieldset: 'icon' },
      { name: 'linkText', title: '按钮文字（双语，可选） / Button text', type: 'localizedString', fieldset: 'action' },
      { ...linkTargetField, name: 'linkTarget', title: '跳转到哪里 / Link target', fieldset: 'action', initialValue: 'none' },
      { name: 'link', title: '自定义链接 / Custom link', type: 'string', fieldset: 'action', hidden: ({ parent }: any) => parent?.linkTarget !== 'custom' },
      { name: 'newTab', title: '新窗口打开 / Open in new tab', type: 'boolean', initialValue: false, fieldset: 'action' },
    ],
  },
  {
    name: 'heroSection',
    title: '首页头图区 / Hero',
    type: 'object',
    fieldsets: [
      { name: 'content', title: '1. 文案 / Copy' },
      { name: 'media', title: '2. 图片 / 视频 / Media' },
      { name: 'actions', title: '3. 按钮 / Buttons' },
    ],
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '首页头图区' },
      enabledField,
      { name: 'title', title: '主标题（双语） / Title', type: 'localizedString', fieldset: 'content' },
      { name: 'subtitle', title: '副标题（双语） / Subtitle', type: 'localizedText', rows: 4, fieldset: 'content' },
      { name: 'backgroundImage', title: '背景图 / Background image', type: 'image', options: { hotspot: true }, fieldset: 'media' },
      { name: 'backgroundVideoUrl', title: '背景视频链接 / Background video URL', type: 'string', fieldset: 'media' },
      ...ctaFields.map((field) => ({ ...field, fieldset: 'actions' })),
    ],
  },
  {
    name: 'featureIconsSection',
    title: '卖点图标区 / Service values',
    type: 'object',
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '卖点图标区' },
      enabledField,
      { name: 'anchorId', title: '内部锚点 / Anchor', type: 'string', hidden: true },
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3 },
      { name: 'items', title: '卡片列表 / Cards', type: 'array', of: [{ type: 'iconLinkCard' }], options: { sortable: true } },
    ],
  },
  {
    name: 'audienceSolutionsSection',
    title: '按人群定制方案区 / Audience solutions',
    type: 'object',
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '按人群定制方案区' },
      enabledField,
      { name: 'anchorId', title: '内部锚点 / Anchor', type: 'string', hidden: true, initialValue: 'audiences' },
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3 },
      { name: 'items', title: '人群方案卡片 / Audience cards', type: 'array', description: '例如 Couples / Family / Executive / Education / VIP Private。', of: [{ type: 'iconLinkCard' }], options: { sortable: true } },
    ],
  },
  {
    name: 'destinationCardsSection',
    title: '目的地卡片区 / Destinations',
    type: 'object',
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '目的地卡片区' },
      enabledField,
      { name: 'anchorId', title: '内部锚点 / Anchor', type: 'string', hidden: true, initialValue: 'destinations' },
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3 },
      { name: 'items', title: '目的地卡片列表 / Destination cards', type: 'array', of: [{ type: 'iconLinkCard' }], options: { sortable: true } },
    ],
  },
  {
    name: 'tourListSection',
    title: '案例 / 灵感区 / Case inspirations',
    type: 'object',
    fieldsets: [{ name: 'basic', title: '1. 基本内容 / Basics' }, { name: 'source', title: '2. 显示哪些案例 / Source' }, { name: 'more', title: '3. 查看更多按钮 / More button' }],
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '案例 / 灵感区' },
      enabledField,
      { name: 'anchorId', title: '内部锚点 / Anchor', type: 'string', hidden: true, initialValue: 'cases' },
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString', fieldset: 'basic' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3, fieldset: 'basic' },
      { name: 'sourceMode', title: '显示方式 / Display mode', type: 'string', fieldset: 'source', options: { list: [{ title: '自动展示最新案例 / Auto latest', value: 'auto' }, { title: '手动挑选案例 / Manual select', value: 'manual' }], layout: 'radio' }, initialValue: 'auto' },
      { name: 'maxItems', title: '显示几项 / Max items', type: 'number', initialValue: 6, fieldset: 'source' },
      { name: 'selectedTours', title: '手动选择案例 / Manual cases', type: 'array', fieldset: 'source', hidden: ({ parent }: any) => parent?.sourceMode !== 'manual', of: [{ type: 'reference', to: [{ type: 'tour' }] }], options: { sortable: true } },
      { name: 'viewMoreText', title: '查看更多按钮文字（双语） / More button text', type: 'localizedString', fieldset: 'more' },
      { ...linkTargetField, name: 'viewMoreTarget', title: '查看更多按钮跳转 / More button target', fieldset: 'more', initialValue: '/contact' },
      { name: 'viewMoreLink', title: '查看更多自定义链接 / More custom link', type: 'string', fieldset: 'more', hidden: ({ parent }: any) => parent?.viewMoreTarget !== 'custom' },
      { name: 'viewMoreNewTab', title: '查看更多新窗口打开 / Open more in new tab', type: 'boolean', initialValue: false, fieldset: 'more' },
    ],
  },
  {
    name: 'articleListSection',
    title: '文章灵感区 / Articles',
    type: 'object',
    fieldsets: [{ name: 'basic', title: '1. 基本内容 / Basics' }, { name: 'source', title: '2. 显示哪些文章 / Source' }, { name: 'more', title: '3. 查看更多按钮 / More button' }],
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '文章灵感区' },
      enabledField,
      { name: 'anchorId', title: '内部锚点 / Anchor', type: 'string', hidden: true, initialValue: 'articles' },
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString', fieldset: 'basic' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3, fieldset: 'basic' },
      { name: 'sourceMode', title: '显示方式 / Display mode', type: 'string', fieldset: 'source', options: { list: [{ title: '自动展示最新文章 / Auto latest', value: 'auto' }, { title: '手动挑选文章 / Manual select', value: 'manual' }], layout: 'radio' }, initialValue: 'auto' },
      { name: 'maxItems', title: '显示几篇 / Max items', type: 'number', initialValue: 3, fieldset: 'source' },
      { name: 'selectedArticles', title: '手动选择文章 / Manual articles', type: 'array', fieldset: 'source', hidden: ({ parent }: any) => parent?.sourceMode !== 'manual', of: [{ type: 'reference', to: [{ type: 'article' }] }], options: { sortable: true } },
      { name: 'viewMoreText', title: '查看更多按钮文字（双语） / More button text', type: 'localizedString', fieldset: 'more' },
      { ...linkTargetField, name: 'viewMoreTarget', title: '查看更多按钮跳转 / More button target', fieldset: 'more', initialValue: '/contact' },
      { name: 'viewMoreLink', title: '查看更多自定义链接 / More custom link', type: 'string', fieldset: 'more', hidden: ({ parent }: any) => parent?.viewMoreTarget !== 'custom' },
      { name: 'viewMoreNewTab', title: '查看更多新窗口打开 / Open more in new tab', type: 'boolean', initialValue: false, fieldset: 'more' },
    ],
  },
  {
    name: 'faqPreviewSection',
    title: '首页 FAQ 区 / FAQ preview',
    type: 'object',
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '首页 FAQ 区' },
      enabledField,
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3 },
      { name: 'maxItems', title: '首页显示几条 / Max items', type: 'number', initialValue: 4 },
      { name: 'viewMoreText', title: '查看更多按钮文字（双语） / More button text', type: 'localizedString', initialValue: { en: 'View All FAQ', zh: '查看全部 FAQ' } },
      { ...linkTargetField, name: 'viewMoreTarget', title: '查看更多按钮跳转 / More button target', initialValue: '/faq' },
      { name: 'viewMoreLink', title: '查看更多自定义链接 / More custom link', type: 'string', hidden: ({ parent }: any) => parent?.viewMoreTarget !== 'custom' },
    ],
  },
  {
    name: 'testimonialsSection',
    title: '用户评价区 / Testimonials',
    type: 'object',
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '用户评价区' },
      enabledField,
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3 },
      { name: 'items', title: '评价列表 / Testimonials', type: 'array', options: { sortable: true }, of: [{ type: 'object', name: 'testimonialItem', fields: [{ name: 'name', title: '姓名 / Name', type: 'string' }, { name: 'country', title: '国家 / 地区 / Country', type: 'string' }, { name: 'quote', title: '评价内容（双语） / Quote', type: 'localizedText', rows: 4 }, { name: 'rating', title: '星级 / Rating', type: 'number', initialValue: 5 }, { name: 'avatar', title: '头像 / Avatar', type: 'image', options: { hotspot: true } }], preview: { select: { title: 'name', subtitle: 'country' } } }] },
    ],
  },
  {
    name: 'statsSection',
    title: '数据统计区 / Stats',
    type: 'object',
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '数据统计区' },
      enabledField,
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 3 },
      { name: 'items', title: '统计项列表 / Stats items', type: 'array', options: { sortable: true }, of: [{ type: 'object', name: 'statItem', fields: [{ name: 'number', title: '数字（双语） / Number', type: 'localizedString' }, { name: 'label', title: '说明（双语） / Label', type: 'localizedString' }], preview: { select: { title: 'number.en', subtitle: 'label.en' } } }] },
    ],
  },
  {
    name: 'ctaSection',
    title: '底部行动按钮区 / CTA',
    type: 'object',
    fields: [
      { name: 'sectionName', title: '后台备注名 / Internal name', type: 'string', initialValue: '底部行动按钮区' },
      enabledField,
      { name: 'title', title: '板块标题（双语） / Title', type: 'localizedString' },
      { name: 'subtitle', title: '板块副标题（双语） / Subtitle', type: 'localizedText', rows: 4 },
      { name: 'backgroundImage', title: '背景图（可选） / Background image', type: 'image', options: { hotspot: true } },
      ...ctaFields,
    ],
  },
]
